// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLxabRvU7BZieJ_W8gciykQS7qzJhblV4',
    appId: '1:410776202310:web:d949fbc9ade45018016e47',
    messagingSenderId: '410776202310',
    projectId: 'sportstribe-12549',
    authDomain: 'sportstribe-12549.firebaseapp.com',
    storageBucket: 'sportstribe-12549.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSlkMLsaohBjwI0D_G7ZM6MGTo--fC48U',
    appId: '1:410776202310:android:b3a437bc07e28319016e47',
    messagingSenderId: '410776202310',
    projectId: 'sportstribe-12549',
    storageBucket: 'sportstribe-12549.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_-9CqhAXzG-UPxnm6uaPNHK2E_BT32Nc',
    appId: '1:410776202310:ios:e66b744ec531a182016e47',
    messagingSenderId: '410776202310',
    projectId: 'sportstribe-12549',
    storageBucket: 'sportstribe-12549.firebasestorage.app',
    androidClientId: '410776202310-54pfgtgsotkjnkg9s5bife92or0v4f2v.apps.googleusercontent.com',
    iosClientId: '410776202310-d4r352vhot9tptghu17u1u34cscva4m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_-9CqhAXzG-UPxnm6uaPNHK2E_BT32Nc',
    appId: '1:410776202310:ios:e66b744ec531a182016e47',
    messagingSenderId: '410776202310',
    projectId: 'sportstribe-12549',
    storageBucket: 'sportstribe-12549.firebasestorage.app',
    androidClientId: '410776202310-54pfgtgsotkjnkg9s5bife92or0v4f2v.apps.googleusercontent.com',
    iosClientId: '410776202310-d4r352vhot9tptghu17u1u34cscva4m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.mapProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLxabRvU7BZieJ_W8gciykQS7qzJhblV4',
    appId: '1:410776202310:web:e0b2db9eca7bc7fb016e47',
    messagingSenderId: '410776202310',
    projectId: 'sportstribe-12549',
    authDomain: 'sportstribe-12549.firebaseapp.com',
    storageBucket: 'sportstribe-12549.firebasestorage.app',
  );
}
